#!/bin/sh
# vim: filetype=sh

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="ff"
export READER="zathura"
export FILE="vu"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
# export HOME="/home/$USER"
# export XDG_CONFIG_HOME="/home/$USER/.config"
# export XDG_DATA_HOME="/home/$USER/.local/share"
# export XDG_CACHE_HOME="/home/$USER/.cache"
# export XDG_DESKTOP_DIR="/home/$USER/temp/desktop"
# export XDG_DOCUMENTS_DIR="/home/$USER/dokumente"
# export XDG_DOWNLOAD_DIR="/home/$USER/shkarkime"
# export XDG_MUSIC_DIR="/home/$USER/muzik"
# export XDG_PICTURES_DIR="/home/$USER/foto"
# export XDG_PUBLICSHARE_DIR="/home/$USER/temp/public"
# export XDG_TEMPLATES_DIR="/home/$USER/temp"
# export XDG_VIDEOS_DIR="/home/$USER/video"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export KODI_DATA="${XDG_DATA_HOME:-$HOME/.local/share}/kodi"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/ansible/ansible.cfg"
export UNISON="${XDG_DATA_HOME:-$HOME/.local/share}/unison"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export WEECHAT_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/weechat"
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export ELECTRUMDIR="${XDG_DATA_HOME:-$HOME/.local/share}/electrum"

# Other program settings:
##export MANPAGER="nvim -c 'set ft=man'"
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-RI
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm

## Fake using a DE for themes to work better
# export DESKTOP_SESSION='GNOME'
# export XDG_SESSION_DESKTOP'GNOME'
# export XDG_CURRENT_DESKTOP='GNOME' #Fake using GNOME de
# export SESSION='GNOME'
# export MDMSESSION='GNOME'
# export GDMSESSION='GNOME'
export QT_QPA_PLATFORMTHEME='qt5ct'	# Have QT use specified theme.
# export QT_STYLE_OVERRIDE='Adwaita-Dark'

##nix extras
export FONTPREVIEW_BG_COLOR="#282828"
export FONTPREVIEW_FG_COLOR="#ebdbb2"
export FONTPREVIEW_PREVIEW_TEXT="ilIrnmo0Oalbgq\nABCDEFGHIJKLM\nNOPQRSTUVWXYZ\nabcdefghijklm\nnopqrstuvwxyz\n1234567890~^*+-_\n!@#$%&()[]{}/|\\\\"
export PF_INFO="ascii title os host kernel uptime pkgs wm shell term res memory palette"
# export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$USER")/bus
