#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:$(find "$HOME/.local/bin" -type d | paste -sd ':' -)"

unsetopt PROMPT_SP >/dev/null 2>&1

# This is the list of exports
. ${XDG_CONFIG_HOME:-$HOME/.config}/shell/exports

# This is the list for lf icons:
. ${XDG_CONFIG_HOME:-$HOME/.config}/shell/lf-icons

test ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc && shortcuts >/dev/null 2>&1 &
setterm --bfreq=30 --blength=100
# test "$(tty)" = "/dev/tty1" && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC" >/dev/null 2>&1

if yay -Qs libxft-bgra >/dev/null 2>&1; then
	# Start graphical server on user's current tty if not already running.
	[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
else
	echo "\033[31mIMPORTANT\033[0m: Note that \033[32m\`libxft-bgra\`\033[0m must be installed for this build of dwm.
Please run:
	\033[32myay -S libxft-bgra-git\033[0m
and replace \`libxft\`. Afterwards, you may start the graphical server by running \`startx\`."
fi

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys ${XDG_DATA_HOME:-$HOME/.local/share}/larbs/ttymaps.kmap 2>/dev/null
